### PR TITLE
HTML to AMP HTML converter

### PR DESCRIPTION
**Pull request by vipervf1**
Added HTML to AMP HTML converter to help with converting RTEs and other resources to valid AMP marktup.

### CODE REVIEW

**Review by scottning — COMMENTED** [review]
"SandboxAttribuiteName" spelling

**Comment by vipervf1** [comment]
@scottning How about now?

**Review by scottning — COMMENTED** [review]
"TestConvertImgWithDimensoinsInSrc" spelling

**Comment by vipervf1** [comment]
@scottning A couple months late, but how about now?

**Review by scottning — APPROVED** [review]

**Pull request merged**
